export 'package:flutter/material.dart';
export 'package:flutter_version370/components/app_image.dart';
export 'package:flutter_version370/components/constants.dart';
export 'package:flutter_version370/components/dimens.dart';
export 'package:flutter_version370/pages/base/widget/custom_bottom_navigation.dart';
export 'package:flutter_version370/pages/base/widget/device_helper.dart';
export '../movie/movie_screen.dart';
export '../cinema/cinema_detail_screen.dart';
export '../base/widget/search_header_widget.dart';